### ISSUE TITLE
In-app items purchase blocked - "The item already purchased. You should let user use this item."

### ISSUE THREAD

**Issue by UmberFunk** [myflashlab/inAppPayments-ANE#5] opened 2016-04-06 21:01 UTC
Hello,

We added several in-app items to our game.  We are testing billing in debug mode. At first, all items were available for purchase multiple times. After some testing one item was blocked. After some more testing, one other item was also blocked. 

Message: 
The item already purchased. You should let user use this item.
Billing.ALREADY_OWNED_ITEM

Billing.IS_DEBUG_MODE = true;
Users are added to LICENCE TESTING in Developer Console;
Latest AIR SDK;
Latest inAppPayments-ANE (from packageV11);
Swf version - 32.

Thanks,
Irakli Geleishvili

**Comment by myflashlab** [comment] 2016-04-07 09:41
I can guess that you are facing this problem in Android, right? let me first give a background information about this. You see, unlike iOS which you have consumable and managed products, on Android side, you only have managed/PERMANENT products. But in our extension, we have added some background works to make both platforms look like each other.

In other words, when you are doing a payment like below on Android,
```actionscript
Billing.doPayment(BillingType.CONSUMABLE, "PRODUCT_ID", "Payload CONSUMABLE", onPurchaseResult);
```
it is first purchased as a managed/PERMANENT product and we are consuming it in the background inside the ANE to make it look like how iOS works.

Saying that, while you are still in the development process, you might have purchased an item using ```BillingType.PERMANENT``` and that will make the purchase permanently. (NOTICE: If you hadn't used the ```BillingType.PERMANENT``` type, then in your app, you should always listen for the purchase result to make sure the payment has gone through successfully)

in such cases, you can still consume your permanent purchase (on Android only) by the following instruction https://github.com/myflashlab/inAppPayments-ANE/blob/master/FD/src/MainFinal.as#L193-L216

**Comment by UmberFunk** [comment] 2016-04-07 10:27
Thanks for your reply.

Yes, we are testing on Android.

We haven't used BillingType.PERMANENT. We ONLY have used BillingType.CONSUMABLE.

The items (which were been blocked) were purchased by us several times and then they were blocked for purchase with this error - Billing.ALREADY_OWNED_ITEM.


This is our code for purchase:

`public static function doPayment(ID, callback):void
{
	if (!isDevice()) return;
	
	function onPurchaseResult($success:int, $data:Purchase, $msg:String):void
	{
		
		if ($msg == Billing.ALREADY_OWNED_ITEM)
		{
			B.Log($msg);
		}
		else if ($msg == Billing.NOT_FOUND_ITEM)
		{
			B.Log($msg);
		}
		else
		{
			B.Log("purchase result message = " + $msg);
		}
		
		
		if ($data)
		{
			B.Log("----------------");
			B.Log("$data.billingType = " +          $data.billingType);
			B.Log("$data.orderId = " +              $data.orderId);
			B.Log("$data.developerPayload = " +     $data.developerPayload);
			B.Log("$data.productId = " +            $data.productId);
			B.Log("$data.purchaseState = " +        $data.purchaseState);
			B.Log("$data.purchaseTime = " +         $data.purchaseTime);
			B.Log("$data.purchaseToken = " +        $data.purchaseToken);
			B.Log("----------------");
		}
		
		
		if (Boolean($success))
		{
			B.Log("--- doPayment SUCCESS ---")
			callback(true, ID);
		}
		else
		{
			B.Log("--- doPayment FAILED ---")
			callback(false, ID);
		}
		
	}
	
	
	B.Log("--- doPayment  ---")
	B.Log("Purchase ID:", ID);
	
	Billing.doPayment(BillingType.CONSUMABLE, ID, "Payload", onPurchaseResult);
}`

**Comment by myflashlab** [comment] 2016-04-07 11:06
You are seeing that particular purchase data in ```Billing.getPurchases(onGetPurchasesResult);``` right?

anyway, please force consume the payment as described above and let me know if you are facing the same problem again?

**Comment by UmberFunk** [comment] 2016-04-07 18:17
No, we see that in onPurchaseResult.

I haven't checked Billing.getPurchases. We had no need for it. We are saving the purchases and progress per user on cloud and we need to be sure that all purchases can be done multiple times. I'll check it anyway and let you know the results.

We can try to reset, and it might work, but what if a user faces the same issue when buying a coinpack second time or for his second ingame account. That would be a bad experience.

I am almost sure there is an issue in the ANE or somewhere else. Not in our code. Our code is same as in guide. Is it possible that Consume failed at some moment and that caused the error?

**Comment by UmberFunk** [comment] 2016-04-08 10:10
From inAppPayments-ANE code example on GitHub:
```
// Please note that consumable products are never saved so you should not expect to receive them with this method.
 Billing.getPurchases(onGetPurchasesResult);.
```

Those items shouldn't be here as we only used BillingType.CONSUMABLE. We never used BillingType.PERMANENT.
```
--- Init Billing Success --- 
--- getPurchases  --- 
---------------- 
purchaseData.orderId = [removed]
purchaseData.productId = char_roobi 
purchaseData.purchaseState = 0 
purchaseData.purchaseTime = 1459934234311 
purchaseData.purchaseToken = [removed]
---------------- 
---------------- 
purchaseData.orderId = [removed] 
purchaseData.productId = coinpack3 
purchaseData.purchaseState = 0 
purchaseData.purchaseTime = 1459897445674 
purchaseData.purchaseToken = [removed]
---------------- 
```

**Comment by myflashlab** [comment] 2016-04-08 10:15
it's probable that all the steps in consuming the purchased product has not been completed. I will mark this as a bug but on your side, please try to see if you can duplicate this problem on your side? While doing that, please pay attention to the returned result. tell us what error message you are receiving when doing the purchase. we'll also test it here on our side and update you as soon as possible.

**Comment by UmberFunk** [comment] 2016-04-08 10:19
Thanks!
We'll continue testing and update you as soon as we'll find anything what might help.

**Comment by myflashlab** [comment] 2016-04-08 13:26
You are right. This happens but in VERY RARE cases when user goes with the purchase but right after paying, if the internet connection goes wrong, the API can't consume the purchase! You don't have to do anything on your side. we will fix this issue and release a new version in the coming days. Thanks for reporting that.

**Comment by UmberFunk** [comment] 2016-04-08 13:36
Awesome! Thanks. I am glad it helped.

We are mainly testing our game in extreme conditions to be sure everything will work when user will have bad connectivity. VPN helps us to simulate it. Testing it in bad connectivity conditions might be the reason we met this issue twice.

**Comment by myflashlab** [comment] 2016-04-08 15:11
Check this fast-fix version and tell me if the problem is now fixed?

[inAppPayments.zip](https://github.com/myflashlab/inAppPayments-ANE/files/210372/inAppPayments.zip)

**Comment by UmberFunk** [comment] 2016-04-08 17:24
That was quick! :)

Thanks. We'll try it and let you know.

**Comment by myflashlab** [comment] 2016-04-12 05:00
We are about to upload that version to the repository. just waiting on your reply before doing that. Please let us know if the problem is fixed in your tests?

**Comment by UmberFunk** [comment] 2016-04-12 10:24
We hadn't time to make enough testing to be sure, as this issue might arrive rarely. Today we'll make more tests and let you know later today or tomorrow morning. Thanks!

**Comment by UmberFunk** [comment] 2016-04-12 13:06
So far no any issues.

We purchased (in testing mode) one of our in-apps ~25 times and made many more purchases on bad bandwidth.

We'll make some more tests but I think if there's still issue, it should have been already spotted by us.

Good job! Thanks!

**Comment by UmberFunk** [comment] 2016-04-12 16:29
We made a lot more tests. This issue seems fixed.

**Comment by UmberFunk** [comment] 2016-04-13 16:52
Did you already updated fixed version? If not, please, can you let me know when you'll do it?

**Comment by myflashlab** [comment] 2016-04-14 08:29
It takes a while before we can actually prepare a file for release version. I'll let you know when the new version is up online.

**Comment by myflashlab** [comment] 2016-04-15 08:51
You can grab V1.0.2 now. Thanks.

**Comment by UmberFunk** [comment] 2016-04-15 10:07
Awesome! Thanks.

**Comment by UmberFunk** [comment] 2016-04-19 14:51
I am unhappy to notify you that this bug still exists. One of our in-apps was blocked again.

**Comment by myflashlab** [comment] 2016-04-19 16:26
hmm, are you using ```flash.data.EncryptedLocalStore``` in your app?

**Comment by UmberFunk** [comment] 2016-04-19 16:33
Thanks.

No, we are not using flash.data.EncryptedLocalStore.

**Comment by myflashlab** [comment] 2016-05-14 04:58
Alright, we came to the following conclusion:

Considering that this is a VERY rare case and only happens if the internet connection of the devices dies after the initial payment and even although we are keeping the failed transaction procedure in a temporary cache to make sure to consume it in the background the next time the ANE runs, if you are still seeing this problem, it makes it even more rare!

but anyhow, to make sure your app would never face a problem, we are adding a "forceConsume" method to the ANE so when you detect the problem, you can force consume the purchase using this method.

This approach will assure you that the payment is completed and consumed as it's supposed to.

*NOTICE:* to those who are reading this ticket, this problem happens only on the Android side and the upcoming V2.0.0 will have this fixed +some other cool features.

**Comment by myflashlab** [comment] 2016-05-16 10:44
Please update to V2.0.0 and find the final solution to this rare problem. [read the changlog here.](https://github.com/myflashlab/inAppPayments-ANE#changelog)

**Closed by myflashlab** 2016-05-16 10:44 UTC
Labels: bug

**Comment by UmberFunk** [comment] 2016-05-16 14:30
Great! Thanks a lot!
