### ISSUE TITLE
Limit of 20 products

### ISSUE THREAD

**Issue by Wpdas** [myflashlab/inAppPayments-ANE#21] opened 2016-09-15 18:18 UTC
The plugin is only giving me support 20 products in the array.

Ex: Billing.init(ANDROID_KEY, ["20 arrays"], Products.iOSProductsClub, onInitResult);

When I add more than 20 productsID the following error message: "Purchase MSG: Error refreshing inventory (querying prices of items). (response: 5:Developer Error)"

**Comment by myflashlab** [comment] 2016-09-16 08:02
is this happening on iOS or Android?

**Comment by Wpdas** [comment] 2016-09-16 11:55
Android.

**Comment by myflashlab** [comment] 2016-09-17 07:27
Well, this is weird. However, check this out and try if what others have suggested can fix your problem?
http://stackoverflow.com/questions/16346030/android-iab-error-refreshing-inventory-querying-prices-of-items-developer-e

**Comment by myflashlab** [comment] 2016-09-22 06:52
Please update us on how it goes...

**Comment by Wpdas** [comment] 2016-09-22 16:43
I can not use another account. I found on the internet some solutions in Java. I can not change your ANE file. The problem continues for me.

**Comment by myflashlab** [comment] 2016-09-27 11:45
We are starting investigating on this to see how we can solve the problem.

**Comment by carlosranoya** [comment] 2017-07-14 22:13
Hi, myflashlab team.

We are developing an application for 3 months, everytime testing with 10 or 11 inAppPurchase products.

Now, just before release version (with more than 20 products) , we discovered that the same issue related here is happening with us.

Do you have any result on the investigation of this problem?  It´s urgent for us.

Thanks.
Carlos.

**Comment by myflashlab** [comment] 2017-07-16 06:32
We are putting resources into fully investigation this issue. we may create a demo/debugging ANE for you so you can send us back logs so we can see what the problem could be. please hold on.

**Comment by rstaliba** [comment] 2017-07-17 16:06
I'm carlosranoya's partner and we're waiting for the debugging ANE to generate the logs and send you. Please send us the link with the debugging version as soon as possible. Thank you.

**Comment by rstaliba** [comment] 2017-07-18 21:24
Hi guys, I think this issue should be labeled as a bug (investigating) and not as an improvement. We have many products (more than 20 product IDs) registered in our app Android (and Google Play console) and we need an urgent solution. We are waiting for the debbuging ANE or a new official version with the problem already solved. We're just waiting for this for the app launch! My company Panapps is a club member and we count on you!

**Comment by rstaliba** [comment] 2017-07-19 18:23
We´ve tried a workaround: calling Billing.init() many times with different lists, but at the second call, the callback is never called. So, unfortunatelly, didn´t work...

**Comment by rstaliba** [comment] 2017-07-27 17:58
Hi myflashlab team, if you do not intend to give priority and solve this issue with agility we will be obliged to buy and use another ANE from another company. My company Panapps is a club member and I would like things to continue this way. What is your position on this specific issue? Can I count on your support or not?

**Comment by myflashlab** [comment] 2017-07-28 04:50
Yes, we will a.s.a.p. The latest news about AIR has been happening so fast and we had to keep up with them... the AR in AIR, the new roadmap for AIR, etc. we will go with a new update for this ANE tomorrow for sure.

**Comment by myflashlab** [comment] 2017-07-29 10:11
Ok, let's see if the problem is now fixed... Please use this test ane instead of the old version and see if it works with more that 20 products?

[inAppPayments.ane.zip](https://github.com/myflashlab/inAppPayments-ANE/files/1184857/inAppPayments.ane.zip)

FYI: we found out that the older billing library had a problem with fetching the items from google server.

**Comment by myflashlab** [comment] 2017-08-01 06:13
Guys! we are waiting for your confirmation to see if the problem is fixed or not! Please use the test ANE and tell us how it works.

**Comment by rstaliba** [comment] 2017-08-02 13:55
Hello myflashlabs team, 
Issue solved! We tested the ANE and it works correctly with more than 20 products. Thanks for the support and we are waiting for the official version as soon as possible.
All the best!

**Comment by myflashlab** [comment] 2017-08-05 08:46
We will be releasing the new version soon. Thanks.

**Closed by myflashlab** 2017-08-05 08:46 UTC
Labels: bug
