### ISSUE TITLE
App crashes when init if there is purchased item

### ISSUE THREAD

**Issue by ghks1353** [myflashlab/inAppPayments-ANE#15] opened 2016-07-07 19:48 UTC
App crashes when calling Billing.init function.
I tried test purchase, purchase was done but app crashed soon.
I opened my app with this ane by test-purchased account, then app crashed.
(New account with no payment access is works well)
No error messages in debug line, just android phone says 'unfortunately, app has stopped'

2.0.0
AIR SDK 21, Android 5.0.1

**Comment by ghks1353** [comment] 2016-07-07 19:59
I also tested this ANE 1.0.2 and it crashes too.

**Comment by myflashlab** [comment] 2016-07-09 15:22
Please post Logcat debug info from when the crash happens so we can see more information about this. https://www.google.com/search?q=how+to+get+logcat+from+Android+studio&ie=utf-8&oe=utf-8&client=firefox-b-ab

**Comment by ghks1353** [comment] 2016-07-10 06:18
[logcat.txt](https://github.com/myflashlab/inAppPayments-ANE/files/355868/logcat.txt)
Here's logcat file. you'll find crash logs at 3309 line or below

--------- beginning of crash

E/AndroidRuntime(10396): FATAL EXCEPTION: Thread-1543

E/AndroidRuntime(10396): Process: air.kr.exfl.avoidtap, PID: 10396

E/AndroidRuntime(10396): java.lang.IllegalArgumentException: java.security.spec.InvalidKeySpecException: java.lang.RuntimeException: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag

E/AndroidRuntime(10396): 	at com.doitflash.inAppBilling.utils.Security.generatePublicKey(Security.java:95)

E/AndroidRuntime(10396): 	at com.doitflash.inAppBilling.utils.Security.verifyPurchase(Security.java:69)

E/AndroidRuntime(10396): 	at com.doitflash.inAppBilling.utils.IabHelper.queryPurchases(IabHelper.java:1002)

E/AndroidRuntime(10396): 	at com.doitflash.inAppBilling.utils.IabHelper.queryInventory(IabHelper.java:585)

E/AndroidRuntime(10396): 	at com.doitflash.inAppBilling.utils.IabHelper.queryInventory(IabHelper.java:562)

E/AndroidRuntime(10396): 	at com.doitflash.inAppBilling.utils.IabHelper$2.run(IabHelper.java:681)

E/AndroidRuntime(10396): 	at java.lang.Thread.run(Thread.java:818)

E/AndroidRuntime(10396): Caused by: java.security.spec.InvalidKeySpecException: java.lang.RuntimeException: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag

E/AndroidRuntime(10396): 	at com.android.org.conscrypt.OpenSSLKey.getPublicKey(OpenSSLKey.java:143)

E/AndroidRuntime(10396): 	at com.android.org.conscrypt.OpenSSLRSAKeyFactory.engineGeneratePublic(OpenSSLRSAKeyFactory.java:47)

E/AndroidRuntime(10396): 	at java.security.KeyFactory.generatePublic(KeyFactory.java:172)

E/AndroidRuntime(10396): 	at com.doitflash.inAppBilling.utils.Security.generatePublicKey(Security.java:86)

E/AndroidRuntime(10396): 	... 6 more

E/AndroidRuntime(10396): Caused by: java.lang.RuntimeException: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag

E/AndroidRuntime(10396): 	at com.android.org.conscrypt.NativeCrypto.d2i_PUBKEY(Native Method)

E/AndroidRuntime(10396): 	at com.android.org.conscrypt.OpenSSLKey.getPublicKey(OpenSSLKey.java:141)

E/AndroidRuntime(10396): 	... 9 more

W/ActivityManager(  832):   Force finishing activity air.kr.exfl.avoidtap/.AppEntry

W/PhoneWindowManagerEx(  832): Call!!!getLGSystemUiVisibility. =0x0

D/StatusBarManagerServiceEx(  832): setLGSystemUiVisibility(0x0)

D/StatusBarManagerServiceEx(  832): manageNaviBtnDisableList userId=0 what=0x0 pkg=WindowManager.LayoutParams

I/ActivityManager(  832): Config changes=480 {0.85 450mcc8mnc ko_KR ldltr sw360dp w360dp h615dp 480dpi nrml long port finger -keyb/v/h -nav/h s.9fontTypeIndex0 defclr=0xfff5f5f5}

V/ActivityManager(  832): Display changed displayId=0

W/PhoneWindowManagerEx(  832): Call!!!getLGSystemUiVisibility. =0x0

D/StatusBarManagerServiceEx(  832): setLGSystemUiVisibility(0x0)

D/StatusBarManagerServiceEx(  832): manageNaviBtnDisableList userId=0 what=0x0 pkg=WindowManager.LayoutParams

I/LGFTMITEM(  300): [GET_FTM][id=2], offset=4096

I/Timeline( 1540): Timeline: Activity_idle id: android.os.BinderProxy@2a6a994b time:260305

I/WindowManager(  832): Screen frozen for +502ms due to Window{9421856 u0 Application Error: air.kr.exfl.avoidtap}

I/LGFTMITEM(  300): [GET_FTM][id=2], offset=4096

I/WindowManager(  832): Rotation completion time: 211848ms

I/ActivityManager(  832): Process air.kr.exfl.avoidtap (pid 10396) has died

**Comment by myflashlab** [comment] 2016-07-11 15:42
well, according to the error message:
>  at com.doitflash.inAppBilling.utils.Security.generatePublicKey(Security.java:95)
java.security.spec.InvalidKeySpecException:

This means that you are entering a wrong public key. [check this out](https://github.com/myflashlab/inAppPayments-ANE#air-usage)

```actionscript
Billing.init("Android KEY from Google Play Console", [Array of Android products], [Array of iOS products], callbackFunction);
```

The first parameter is the public key you can find in your Google play console. similar to this one: http://prntscr.com/b5zmlx

**Comment by ghks1353** [comment] 2016-07-12 00:46
Wow, it's my fault. I entered a wrong key to my application.
![image](https://cloud.githubusercontent.com/assets/6275109/16751508/04091278-4815-11e6-9e6e-94ff36abf525.png)

But I have another problem, If I try to restore, there are dummy purchased items in array but if I try to purchase my item, it says "already owned item".
I tried to clearing cache, reinstall my app but dummy items still there.

Also the purchased array not containing my purchased item information.

**Comment by myflashlab** [comment] 2016-07-14 09:49
Please send us a demo project so we can duplicate this problem and find a fix, Thanks.

**Comment by Wpdas** [comment] 2016-07-20 17:55
I got the same error:
flash.data::SQLStatement/internalExecute
flash.data::SQLStatement/execute
Funcion/<anonymous>
Funcion/<anonymous>
Funcion/<anonymous>

Was working normal at the beginning. After a while gave this bug.

**Comment by myflashlab** [comment] 2016-07-20 18:06
That would be great if you can tell us how we can reproduce this possible bug...

**Comment by Wpdas** [comment] 2016-07-20 19:46
Yes, so:

1 - I published the 0.0.2 version of the application for testing. (On Billing);
2 - Start the application and press "OK" in the "Demo" display;
3 - Reading of the items that are available for purchase is made;
4 - I make a purchase through the product ID (formerly operated);
4.1 - After making several test purchases stopped working when you debug (and present these errors above);
4.2 - When I ask the shopping list in debug mode, it generates the same error above;
5 - When I do some shopping in release mode, the purchase is made;
6 - When I ask the shopping list in release mode, returns a huge list of zero purchases;

So, I can not verify the purchases that have been made.

If you want, I can send you my project (using your reference "FD") and a signature key for you to check. In this particular case you pass me your email for free test access.

Follow my application.xml:

<?xml version="1.0" encoding="utf-8" standalone="no" ?>

<application xmlns="http://ns.adobe.com/air/application/22.0">
  <id>com.360e1.galofanatikids</id>
  <versionNumber>0.0.2</versionNumber>
  <versionLabel>0.0.2</versionLabel>
  <filename>Galo Fanatikids</filename>
  <description/>
  <name>Galo Fanatikids</name>  
  <copyright/>
  <initialWindow>
    <content>Fanatikids.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>true</fullScreen>
    <aspectRatio>landscape</aspectRatio>
    <renderMode>gpu</renderMode>
    <autoOrients>true</autoOrients></initialWindow>
  <icon>
	  <image144x144>icons/144x144.png</image144x144>
	  <image114x114>icons/114x114.png</image114x114>
	  <image96x96>icons/96x96.png</image96x96>
    <image72x72>icons/72x72.png</image72x72>
    <image48x48>icons/48x48.png</image48x48>
    <image36x36>icons/36x36.png</image36x36>
  </icon>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
  <android>
    <manifestAdditions>
		<![CDATA[
		
		<manifest android:installLocation="auto">

			<uses-permission android:name="android.permission.INTERNET"/>
			<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
			<uses-permission android:name="android.permission.RECORD_AUDIO"/>
			<uses-permission android:name="android.permission.DISABLE_KEYGUARD"/>
			<uses-permission android:name="android.permission.WAKE_LOCK"/>
			<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
			<uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
			
			
			<uses-permission android:name="com.android.vending.BILLING"/>
			
			<application>
				
				<activity>
					<intent-filter>
						<action android:name="android.intent.action.MAIN" />
						<category android:name="android.intent.category.LAUNCHER" />
					</intent-filter>
					<intent-filter>
						<action android:name="android.intent.action.VIEW" />
						<category android:name="android.intent.category.BROWSABLE" />
						<category android:name="android.intent.category.DEFAULT" />
					</intent-filter>
				</activity>
				
				
				<activity android:name="com.doitflash.inAppBilling.utils.MyPurchase" android:theme="@style/Theme.Transparent" />

			</application>
			
	    </manifest>]]>
		
	</manifestAdditions>
  </android>
  <supportedLanguages>pt</supportedLanguages>
  <extensions>
    <extensionID>com.myflashlab.air.extensions.billing</extensionID>
  </extensions>
</application>

**Comment by myflashlab** [comment] 2016-07-20 19:59
Thanks for the detailed information. We'll try to see what could have gone wrong. 

It seems like you are testing on Android, could you also try to produce the problem on the iOS too? See if that happens on iOS also or not.

**Comment by Wpdas** [comment] 2016-07-20 20:03
Only on Android, produce for iOS will be the next step.

Thanks for listening. We will buy your extension, only need a solution for this.

**Comment by raresn** [comment] 2016-09-05 10:35
Same SQLStatement/internalExecute()
For me it started from another old extension (pozirk) and a combination of "adb.exe shell pm clear com.android.vending". Found out something remains unconsumed and may be cleared by the old extension we were using.
Bottom line is that a product is owned in play store and will not show up in restore purchases. This is why we moved away from old extension.

**Comment by myflashlab** [comment] 2016-09-07 08:39
As far as the null purchase items, we have not been able to duplicate the problem! guys, would you try what @raresn suggested and report back on how things went?

**Comment by myflashlab** [comment] 2016-09-17 08:07
Ok, I'm closing down the issue now as it's been more than 10 days we waited on a report. So it seems the problem is solved. However, if you still have questions about this, please feel free to reopen the issue so we can continue.

**Closed by myflashlab** 2016-09-17 08:07 UTC

**Comment by Samuramu** [comment] 2017-08-23 11:03
I seem to have the issue on iOS.
At some point during development, getting purchases / restoring purchases started crashing the app on a specific device. 
It works correctly on two other devices using a different iTunes account, but on my iPad 3 it just crashes.
Trying to understand what can be done to prevent this, as I suspect some users who reported being unable to restore purchases on older versions might have had this issue.

**Comment by raresn** [comment] 2017-08-23 19:28
Yeah.. I couldn't reproduce on my test devices and since a lot of the people who were purchasing/restoring the purchases complained about the issue I had to switch to the ANE Adobe provides for iOS :( - Lucky for me the problem disappeared but I would simply love to know if someone can replicate so we can find a solution to the problem.
I wanna note that I had no problem on Android.

**Comment by myflashlab** [comment] 2017-08-24 11:53
This problem was originated on the Android side. Please open a new ticket with xcode error logs so we can investigate and find the possible problem and solve it.
