### ISSUE TITLE
Android build price in products array is negative value

### ISSUE THREAD

**Issue by jayasuryaiplotz** [myflashlab/inAppPayments-ANE#31] opened 2017-02-02 08:47 UTC
I have 4 products configured in Google Play. Two products price in Billing.products is correct but for other two it is a negative value. 
Developer console price is set in Philippine Peso. 490.00 and 1,240.00 is correct in other currency. 2,490.00 and 4,980.00 is  negative value in Indian Rupee. Thai Baht, last product prize is negative.
In Developer console Local prices is correct for all.

V2.0 and 2.1 same result.

**Comment by MyMyGames** [comment] 2017-03-15 02:38
I have simular problem.
Developer console price:
....
Big Pack of Coins USD 19,99 (	RUB 1 190,00)
Huge Pack of Coins USD 49,99 (RUB 2 999,00)
Epic Pack of Coins USD 99,99 (RUB 5 999,00)

In app (Russian rubles):
Big Pack of Coins  RUB 1 190,00
Huge Pack of Coins RUB -1304,97
Epic Pack of Coins RUB 1604.03

**Comment by ze0nni** [comment] 2017-04-24 16:13
I have same effect

**Comment by myflashlab** [comment] 2017-04-25 13:10
Guys, we'd love to know why this is happening but we are not able to duplicate this problem! We are adding sample expensive prices but they are returned all OK. Moreover, the ANE does nothing in returning the prices, the Google SDK is passing the prices to begin with. 🤔

**Comment by sts12345** [comment] 2017-07-20 10:10
Prices from Google comes multiplied by 1 000 000. So RUB 2 999,00 will come with value 2 999 000 000. this is bigger than max INT value 2 147 483 647 and we have overflow to negative value.
I think, if your change all INT variables to LONG INT or DOBLE INT (don't know what language you use) in your ANE it will fix the problem.

**Comment by myflashlab** [comment] 2017-07-20 10:45
🤔 will try that @sts12345 thanks for the suggestion

**Comment by myflashlab** [comment] 2017-07-29 10:21
please test this demo ane instead of the current one and see if the problem is fixed? https://github.com/myflashlab/inAppPayments-ANE/issues/21#issuecomment-318818774

We are planning on releasing a new version which will have many bug fixes including this one. Let us know if this issue is fixed in the linked ANE above?

**Comment by myflashlab** [comment] 2017-08-01 06:14
🔈  Guys! we are waiting for your confirmation to see if the problem is fixed or not! Please use the test ANE and tell us how it works.

**Comment by misterPitty** [comment] 2017-08-01 10:14
In my case problem was solved so i am waiting for release build with fixes.

**Comment by myflashlab** [comment] 2017-08-05 08:45
We will be releasing a new version soon with this fix.

**Closed by myflashlab** 2017-08-05 08:45 UTC
Labels: bug
